### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Alejandro-Trave-Traffic-lights#1]
# Revisión - Aprobado :white_check_mark:

## Feedback
- Buen proyecto @Atravep 🐱‍💻

## Estilo de código y limpieza
- Bien resuelto
- Buen uso del `useState` y del `useEffect`

## Mejores prácticas/comentarios
- Muy buen trabajo Alejandro. Me encanta el diseño. 
- En tu componente `Home` puedes importar directamente tu componente `TrafficLight` sin necesitadad de meterlo dentro de un `<div>`
![Captura de pantalla de 2024-04-28 18-18-02](https://github.com/4GeeksAcademy/Alejandro-Trave-Traffic-lights/assets/139759297/15d6a8a5-ed3f-4976-8569-4da55e85695e)

**Comment by Atravep** [comment]
Gracias por la revisión, Edu!.
